//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiPeluqueria.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bd_tienda_belleza_finalEntities : DbContext
    {
        public bd_tienda_belleza_finalEntities()
            : base("name=bd_tienda_belleza_finalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cargoempleado> cargoempleadoes { get; set; }
        public virtual DbSet<categoriaproducto> categoriaproductoes { get; set; }
        public virtual DbSet<ciudad> ciudads { get; set; }
        public virtual DbSet<cliente> clientes { get; set; }
        public virtual DbSet<descuentomayorista> descuentomayoristas { get; set; }
        public virtual DbSet<detalleventa> detalleventas { get; set; }
        public virtual DbSet<direccion> direccions { get; set; }
        public virtual DbSet<empleado> empleadoes { get; set; }
        public virtual DbSet<formapago> formapagoes { get; set; }
        public virtual DbSet<producto> productoes { get; set; }
        public virtual DbSet<productopromocion> productopromocions { get; set; }
        public virtual DbSet<serviciodomicilio> serviciodomicilios { get; set; }
        public virtual DbSet<telefono> telefonoes { get; set; }
        public virtual DbSet<tipocliente> tipoclientes { get; set; }
        public virtual DbSet<tipodocumento> tipodocumentoes { get; set; }
        public virtual DbSet<tipotelefono> tipotelefonoes { get; set; }
        public virtual DbSet<usuario> usuarios { get; set; }
        public virtual DbSet<venta> ventas { get; set; }
    }
}
