//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiPeluqueria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class productopromocion
    {
        public int id_productopromocion { get; set; }
        public int id_productoprom { get; set; }
        public int id_producto { get; set; }
        public Nullable<int> cantidadproducto { get; set; }
    
        public virtual producto producto { get; set; }
    }
}
