//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiPeluqueria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class telefono
    {
        public int id_telefono { get; set; }
        public int id_tipotelefono { get; set; }
        public string numerotelefono { get; set; }
        public int id_cliente { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual tipotelefono tipotelefono { get; set; }
    }
}
