//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiPeluqueria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class venta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public venta()
        {
            this.detalleventas = new HashSet<detalleventa>();
            this.serviciodomicilios = new HashSet<serviciodomicilio>();
        }
    
        public int id_venta { get; set; }
        public int id_cliente { get; set; }
        public int id_empleado { get; set; }
        public int id_formapago { get; set; }
        public int id_detalleventa { get; set; }
        public System.DateTime fechaventa { get; set; }
        public decimal subtotal { get; set; }
        public Nullable<decimal> descuento { get; set; }
        public Nullable<decimal> impuestos { get; set; }
        public decimal total { get; set; }
        public string comentarios { get; set; }
        public Nullable<bool> domicilio { get; set; }
    
        public virtual cliente cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalleventa> detalleventas { get; set; }
        public virtual empleado empleado { get; set; }
        public virtual formapago formapago { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<serviciodomicilio> serviciodomicilios { get; set; }
    }
}
